id: P003187
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 10:46:09.390610
source_metadata:
  id: bdr:W2DB25427
  title: མི་དབང་རྟོགས་བརྗོད
  author: ''
  volumes:
    214952da049b480baadc0011052bb85d:
      image_group_id: I1PD36295
      title: ''
      volume_number: 1
      total_pages: 890
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
